// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace ClassLibrary2.Model
{
    public partial class Enrollment
    {
        public int Id { get; set; }
        public int Studentid { get; set; }
        public int Classid { get; set; }

        public virtual Subject Class { get; set; }
        public virtual Student Student { get; set; }
    }
}